"""init

Revision ID: 4822b372f17f
Revises: 8b0210232145
Create Date: 2024-12-09 08:05:56.820824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4822b372f17f'
down_revision = '8b0210232145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userinfo', 'cosoyte_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_userinfo_cosoyte_id', table_name='userinfo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_userinfo_cosoyte_id', 'userinfo', ['cosoyte_id'], unique=False)
    op.alter_column('userinfo', 'cosoyte_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
