"""init

Revision ID: 6399f92797cd
Revises: cab7430fff5f
Create Date: 2024-12-09 07:38:25.545153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6399f92797cd'
down_revision = 'cab7430fff5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appinfo', sa.Column('cosoyte_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'appinfo', 'cosoyte', ['cosoyte_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appinfo', type_='foreignkey')
    op.drop_column('appinfo', 'cosoyte_id')
    # ### end Alembic commands ###
