"""init

Revision ID: 6a10d37f402d
Revises: 6399f92797cd
Create Date: 2024-12-09 07:54:05.349021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a10d37f402d'
down_revision = '6399f92797cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cosoyte', sa.Column('captren_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_cosoyte_captren_id'), 'cosoyte', ['captren_id'], unique=False)
    op.create_foreign_key(None, 'cosoyte', 'cosoyte', ['captren_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cosoyte', type_='foreignkey')
    op.drop_index(op.f('ix_cosoyte_captren_id'), table_name='cosoyte')
    op.drop_column('cosoyte', 'captren_id')
    # ### end Alembic commands ###
