"""init

Revision ID: 8b0210232145
Revises: 6a10d37f402d
Create Date: 2024-12-09 08:04:38.790071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0210232145'
down_revision = '6a10d37f402d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cosoyte', sa.Column('userinfo_id', sa.String(), nullable=True))
    op.drop_index('ix_cosoyte_appinfo_id', table_name='cosoyte')
    op.create_index(op.f('ix_cosoyte_userinfo_id'), 'cosoyte', ['userinfo_id'], unique=False)
    op.drop_constraint('cosoyte_appinfo_id_fkey', 'cosoyte', type_='foreignkey')
    op.create_foreign_key(None, 'cosoyte', 'userinfo', ['userinfo_id'], ['id'])
    op.drop_column('cosoyte', 'appinfo_id')
    op.drop_constraint('donvi_appinfo_id_fkey', 'donvi', type_='foreignkey')
    op.create_foreign_key(None, 'donvi', 'userinfo', ['appinfo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'donvi', type_='foreignkey')
    op.create_foreign_key('donvi_appinfo_id_fkey', 'donvi', 'appinfo', ['appinfo_id'], ['id'])
    op.add_column('cosoyte', sa.Column('appinfo_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cosoyte', type_='foreignkey')
    op.create_foreign_key('cosoyte_appinfo_id_fkey', 'cosoyte', 'appinfo', ['appinfo_id'], ['id'])
    op.drop_index(op.f('ix_cosoyte_userinfo_id'), table_name='cosoyte')
    op.create_index('ix_cosoyte_appinfo_id', 'cosoyte', ['appinfo_id'], unique=False)
    op.drop_column('cosoyte', 'userinfo_id')
    # ### end Alembic commands ###
