"""init

Revision ID: b82c7a430600
Revises: f139f4ebf0bd
Create Date: 2024-12-09 05:23:42.014807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82c7a430600'
down_revision = 'f139f4ebf0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
