"""init

Revision ID: cab7430fff5f
Revises: b82c7a430600
Create Date: 2024-12-09 07:32:28.279441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cab7430fff5f'
down_revision = 'b82c7a430600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cosoyte',
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ma_donvi', sa.String(length=255), nullable=True),
    sa.Column('ten_donvi', sa.String(), nullable=False),
    sa.Column('tenkhongdau', sa.String(), nullable=True),
    sa.Column('level_donvi', sa.SmallInteger(), nullable=False),
    sa.Column('hinhthuchintochuc', sa.String(), nullable=True),
    sa.Column('xaphuong_id', sa.String(), nullable=True),
    sa.Column('xaphuong', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quanhuyen_id', sa.String(), nullable=True),
    sa.Column('quanhuyen', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tinhthanh_id', sa.String(), nullable=True),
    sa.Column('tinhthanh', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quocgia_id', sa.String(), nullable=True),
    sa.Column('quocgia', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sonha_tenduong', sa.String(), nullable=True),
    sa.Column('diachi', sa.String(), nullable=True),
    sa.Column('tuyendonvi_id', sa.String(), nullable=True),
    sa.Column('email_donvi', sa.String(length=255), nullable=True),
    sa.Column('dienthoai_donvi', sa.String(length=63), nullable=True),
    sa.Column('appinfo_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['appinfo_id'], ['appinfo.id'], ),
    sa.ForeignKeyConstraint(['quanhuyen_id'], ['quanhuyen.id'], ),
    sa.ForeignKeyConstraint(['quocgia_id'], ['quocgia.id'], ),
    sa.ForeignKeyConstraint(['tinhthanh_id'], ['tinhthanh.id'], ),
    sa.ForeignKeyConstraint(['tuyendonvi_id'], ['tuyendonvi.id'], ),
    sa.ForeignKeyConstraint(['xaphuong_id'], ['xaphuong.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cosoyte_appinfo_id'), 'cosoyte', ['appinfo_id'], unique=False)
    op.create_index(op.f('ix_cosoyte_quanhuyen_id'), 'cosoyte', ['quanhuyen_id'], unique=False)
    op.create_index(op.f('ix_cosoyte_quocgia_id'), 'cosoyte', ['quocgia_id'], unique=False)
    op.create_index(op.f('ix_cosoyte_tinhthanh_id'), 'cosoyte', ['tinhthanh_id'], unique=False)
    op.create_index(op.f('ix_cosoyte_tuyendonvi_id'), 'cosoyte', ['tuyendonvi_id'], unique=False)
    op.create_index(op.f('ix_cosoyte_xaphuong_id'), 'cosoyte', ['xaphuong_id'], unique=False)
    op.add_column('donvi', sa.Column('ma_donvi', sa.String(length=255), nullable=True))
    op.add_column('donvi', sa.Column('ten_donvi', sa.String(), nullable=False))
    op.drop_column('donvi', 'ten_coso')
    op.drop_column('donvi', 'ma_coso')
    op.add_column('profile_user', sa.Column('cosoyte_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_profile_user_cosoyte_id'), 'profile_user', ['cosoyte_id'], unique=False)
    op.create_foreign_key(None, 'profile_user', 'cosoyte', ['cosoyte_id'], ['id'])
    op.add_column('userinfo', sa.Column('cosoyte_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_userinfo_cosoyte_id'), 'userinfo', ['cosoyte_id'], unique=False)
    op.create_foreign_key(None, 'userinfo', 'cosoyte', ['cosoyte_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userinfo', type_='foreignkey')
    op.drop_index(op.f('ix_userinfo_cosoyte_id'), table_name='userinfo')
    op.drop_column('userinfo', 'cosoyte_id')
    op.drop_constraint(None, 'profile_user', type_='foreignkey')
    op.drop_index(op.f('ix_profile_user_cosoyte_id'), table_name='profile_user')
    op.drop_column('profile_user', 'cosoyte_id')
    op.add_column('donvi', sa.Column('ma_coso', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('donvi', sa.Column('ten_coso', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('donvi', 'ten_donvi')
    op.drop_column('donvi', 'ma_donvi')
    op.drop_index(op.f('ix_cosoyte_xaphuong_id'), table_name='cosoyte')
    op.drop_index(op.f('ix_cosoyte_tuyendonvi_id'), table_name='cosoyte')
    op.drop_index(op.f('ix_cosoyte_tinhthanh_id'), table_name='cosoyte')
    op.drop_index(op.f('ix_cosoyte_quocgia_id'), table_name='cosoyte')
    op.drop_index(op.f('ix_cosoyte_quanhuyen_id'), table_name='cosoyte')
    op.drop_index(op.f('ix_cosoyte_appinfo_id'), table_name='cosoyte')
    op.drop_table('cosoyte')
    # ### end Alembic commands ###
